version: '3'
services:
  users:
    build: .
    command: npm start users
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/users/src:/app/src
      - ./package.json:/app/package.json

  gateway:
    build: .
    command: npm start clarity-gateway
    ports:
      - "3000:3000"
    depends_on:
      - users
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/clarity-gateway/src:/app/src
      - ./package.json:/app/package.json
      
# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     command: npm start clarity-gateway
#     environment:
#       - NODE_ENV=development
#     develop:
#       watch:
#         - action: sync
#           path: ./apps/clarity-gateway/src
#           target: /app/src
#         - action: sync
#           path: ./package.json
#           target: /app/package.json
#         - action: rebuild
#           path: ./package.json

# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     command: npm run start:dev
#     develop:
#       watch:
#         - action: sync
#           path: ./src
#           target: /app/src
#         - action: sync
#           path: ./package.json
#           target: /app/package.json
#         - action: rebuild
#           path: ./package.json